import { Metadata } from "next";
import Link from "next/link";
import { SITE_URL } from "@/lib/siteConfig";
import SchemaScript from "@/components/SchemaScript";
import { webApplicationSchema } from "@/lib/schema";

const TITLE = "How to Start Investing with Little Money | Index Funds Guide";
const DESCRIPTION =
  "Learn how to start investing with little money. Master the basics of compound interest, low-cost index funds, ETFs, and long-term passive wealth creation.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/investing` },
};

export default function InvestingPage() {
  const schema = webApplicationSchema({
    name: TITLE,
    description: DESCRIPTION,
    path: "/investing",
  });

  return (
    <div className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8 space-y-12">
      <SchemaScript schemas={schema} />

      {/* Header */}
      <div className="text-center max-w-2xl mx-auto space-y-3">
        <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white">
          How to Start Investing <span className="text-emerald-600 dark:text-emerald-400">with Little Money</span>
        </h1>
        <p className="text-sm text-gray-500 dark:text-gray-400">
          You don&apos;t need thousands of dollars to start building wealth. Learn the power of index funds, ETFs, and compound interest.
        </p>
      </div>

      {/* Main Educational Article Grid */}
      <div className="max-w-3xl mx-auto space-y-8 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
        {/* Core Concept 1 */}
        <section className="bg-white dark:bg-gray-900 border border-gray-150 dark:border-gray-800 p-6 rounded-xl space-y-3">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <span>📈</span> 1. The Magic of Compound Interest
          </h2>
          <p>
            Compound interest is the interest you earn on interest. Over 10, 20, or 30 years, it turns tiny monthly contributions into significant sums of money.
          </p>
          <p>
            For example: If you invest just <strong>$100 a month</strong> starting at age 25, assuming an 8% average annual return, you will have over <strong>$350,000</strong> by age 65. Most of that total is money generated by interest, not your own pocket.
          </p>
        </section>

        {/* Core Concept 2 */}
        <section className="bg-white dark:bg-gray-900 border border-gray-150 dark:border-gray-800 p-6 rounded-xl space-y-3">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <span>🛡️</span> 2. What are Index Funds & ETFs?
          </h2>
          <p>
            Instead of trying to pick individual stocks (which is risky and often fails), index funds and Exchange-Traded Funds (ETFs) let you buy a tiny slice of hundreds of companies at once.
          </p>
          <p>
            An ETF that tracks the S&P 500 (like VOO or SPY) gives you instant ownership in the 500 largest US companies—including Apple, Microsoft, Amazon, and Google. If one company fails, your portfolio is protected by the success of the other 499.
          </p>
        </section>

        {/* Core Concept 3 */}
        <section className="bg-white dark:bg-gray-900 border border-gray-150 dark:border-gray-800 p-6 rounded-xl space-y-3">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <span>💰</span> 3. How to Start with Just $5 or $10
          </h2>
          <p>
            Modern brokerage platforms offer <strong>fractional shares</strong>. This means if a stock or ETF costs $400 per share, you can buy $5 worth of it (a fraction of a share).
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Automate:</strong> Set up a recurring transfer of $10/week to your investment app.</li>
            <li><strong>Keep Fees Low:</strong> Use commission-free brokerages so fees don&apos;t eat your small contributions.</li>
            <li><strong>Reinvest Dividends:</strong> Enable DRIP (Dividend Reinvestment Plan) to buy more shares automatically.</li>
          </ul>
        </section>
      </div>

      {/* CTA Box */}
      <div className="bg-emerald-50/50 dark:bg-emerald-950/10 border border-emerald-100 dark:border-emerald-900/50 p-6 rounded-2xl max-w-2xl mx-auto text-center space-y-4">
        <h2 className="text-lg font-bold text-gray-900 dark:text-white">Calculate your net take-home salary</h2>
        <p className="text-xs text-gray-600 dark:text-gray-400">
          Want to know how much cash you have left over to invest? Use our take-home salary estimator tool.
        </p>
        <Link
          href="/salary"
          className="inline-block px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold rounded-lg shadow-sm"
        >
          Go to Salary Calculator
        </Link>
      </div>
    </div>
  );
}
